# Auto-generated by asn1ate on 2015-03-18 20:36:46.113234
from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class FooQuestion(univ.Sequence):
    pass


FooQuestion.componentType = namedtype.NamedTypes(
    namedtype.NamedType('trackingNumber', univ.Integer()),
    namedtype.NamedType('question', char.IA5String().subtype(subtypeSpec=constraint.ValueSizeConstraint(1, 40)))
)


class FooAnswer(univ.Sequence):
    pass


FooAnswer.componentType = namedtype.NamedTypes(
    namedtype.NamedType('questionNumber', univ.Integer()),
    namedtype.NamedType('answer', univ.Boolean())
)


